Alma9 and dirac 8.0.53
Fails during build with
```
------
 > [18/22] RUN nohup bash -c '/bin/entrypoint.sh &' &&     ln -s /var/lib/mysql/mysql.sock /tmp/mysql.sock &&     su dirac -c './install_site.sh -v ${dirac_version} install.cfg && ./post_install.sh ${dirac_pilot_version}':
55.98 2024-10-09 10:19:35 UTC dirac-setup-site [130586465075648] DEBUG: Trying to connect to: dips://dirac-tuto:9135/Configuration/Server
55.98 2024-10-09 10:19:35 UTC dirac-setup-site [130586465075648] WARN: Issue getting socket: <DIRAC.Core.DISET.private.Transports.M2SSLTransport.SSLTransport object at 0x76c484cd1c50> : ('dips', 'dirac-tuto', 9135, 'Configuration/Server') : [Errno 111] Connection refused:ConnectionRefusedError(111, 'Connection refused')
55.98 2024-10-09 10:19:35 UTC dirac-setup-site [130586465075648] INFO: Retry connection : 2 to dips://dirac-tuto:9135/Configuration/Server
55.98 2024-10-09 10:19:35 UTC dirac-setup-site [130586465075648] INFO: Waiting 2.000000 seconds before retry all service(s)
57.98 2024-10-09 10:19:37 UTC dirac-setup-site [130586465075648] DEBUG: Already given a valid url dips://dirac-tuto:9135/Configuration/Server
57.98 2024-10-09 10:19:37 UTC dirac-setup-site [130586465075648] DEBUG: Trying to connect to: dips://dirac-tuto:9135/Configuration/Server
57.98 2024-10-09 10:19:37 UTC dirac-setup-site [130586465075648] WARN: Issue getting socket: <DIRAC.Core.DISET.private.Transports.M2SSLTransport.SSLTransport object at 0x76c484cc6910> : ('dips', 'dirac-tuto', 9135, 'Configuration/Server') : [Errno 111] Connection refused:ConnectionRefusedError(111, 'Connection refused')
57.98 2024-10-09 10:19:37 UTC dirac-setup-site [130586465075648] WARN: Can't update from server Error while updating from dips://dirac-tuto:9135/Configuration/Server: [Errno 111] Connection refused:ConnectionRefusedError(111, 'Connection refused')
57.98 ERROR: Reason(s):
57.98   [Errno 111] Connection refused:ConnectionRefusedError(111, 'Connection refused')
------
Dockerfile:83
--------------------
  82 |     # In tutorial the setup is configured as diracuser user, but here we use dirac user, so not to have diracos installed twice.
  83 | >>> RUN nohup bash -c '/bin/entrypoint.sh &' && \
  84 | >>>     ln -s /var/lib/mysql/mysql.sock /tmp/mysql.sock && \
  85 | >>>     su dirac -c './install_site.sh -v ${dirac_version} install.cfg && ./post_install.sh ${dirac_pilot_version}'
  86 |
--------------------
ERROR: failed to solve: process "/bin/sh -c nohup bash -c '/bin/entrypoint.sh &' &&     ln -s /var/lib/mysql/mysql.sock /tmp/mysql.sock &&     su dirac -c './install_site.sh -v ${dirac_version} install.cfg && ./post_install.sh ${dirac_pilot_version}'" did not complete successfully: exit code: 255
```